- name: add application user
  ansible.builtin.user:
    name: roboshop
- name: remove old app directory
  ansible.builtin.file:
    path: /app
    state: absent
- name: create new app directory
  ansible.built.in.file:
    path: /app
    state: directory

- name: download and extract app content
  ansible.builtin.unarchive:
    src:  https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: yes

